Sprint 1
AlexanderKara/yandex-praktikum-middle.messenger.praktikum.yandex pull request #6
Opened 2023-04-07 15:24 UTC by AlexanderKara

**Выполнены требования к проекту 1 спринта**
1. Нарисован прототип в Figma, ссылка добавлена в readme.md
2. Подключен шаблонизатор Handlebars
3. Настроена сборка проекта с помощью Parcel
4. Созданы страницы проекта согласно ТЗ, в соответствии с отрисованным прототипом, страницы на шаблонах
5. Стили в scss
6. Код разбит на модули
7. Настроена локальная раздача статики через Express
8. Проект выложен на Netlify, настроен автодеплой, ссылка добавлена в readme.md
9. Заменен readme.md, в него добавлено краткое описание, инструкции и ссылки.
11. В ветку main загружен только src
12. Проект открывается на 3000 порту по `npm run start`
13. Репозиторий публичный.
14. dist и node_modules помещены в .gitignore

2023-04-08 13:25 UTC, podlovchenko requested changes
Привет, в целом все хорошо) 

По чеклисту необходимо `Укажите версию NodeJS в .nvmrc или engine в package.json. Она должна быть не ниже 12;`

2023-04-08 13:25 UTC, podlovchenko commented on .gitignore
> +.idea
В проекте в некоторых файлах есть ошибка EOF
Для git важно наличие пустой строки в конце файла
https://stackoverflow.com/questions/5813311/whats-the-significance-of-the-no-newline-at-end-of-file-log

2023-04-08 13:25 UTC, podlovchenko commented on package.json
> +    "build": "npm i && parcel build src/index.html"
Не нужно каждый раз делать npm i

2023-04-08 13:25 UTC, podlovchenko commented on server.js
> +const PORT = 3000;
Часто требуется возможность получить порт снаружи скрипта, не изменяя код, это можно сделать через переменное окружение:
process.env.PORT || PORT;
https://nodejs.org/dist/latest-v8.x/docs/api/process.html

2023-04-08 13:25 UTC, podlovchenko commented on src/pages/chat/menu/style.scss
> +      a {
Лучше использовать классы, а не теги
Статья на эту тему https://frontstuff.io/you-need-to-stop-targeting-tags-in-css

2023-04-08 13:25 UTC, podlovchenko commented on src/pages/chat/messages/header/style.scss
> +    background: #DEE2E3;
Цвета лучше указывать через css переменные, так будет понятнее, что это за цвет при просмотре кода и проще редактировать цвета по всему проекту

2023-04-09 11:33 UTC, AlexanderKara commented on server.js
> +const PORT = 3000;
спасибо, поправил

2023-04-09 11:34 UTC, AlexanderKara commented on package.json
> +    "build": "npm i && parcel build src/index.html"
исправил

2023-04-09 11:35 UTC, AlexanderKara commented on src/pages/chat/messages/header/style.scss
> +    background: #DEE2E3;
так и делал, но в этом месте почему-то пропустил, исправлю, спасибо

2023-04-09 12:31 UTC, podlovchenko commented
Спасибо за правки, работу принимаю)

2023-04-09 12:52 UTC, merged